### ISSUE TITLE
Error in Log: Core: Exception handler (WEB): Uncaught TYPO3 Exception: Mindshape\MindshapeCookieConsent\Service\CookieConsentService::__construct(): Argument #2 ($configurationRepository) must be of type Mindshape\MindshapeCookieConsent\Domain\Repository\ConfigurationRepository

### ISSUE THREAD

**Issue by cbaumstark** [mindshape-GmbH/mindshape_cookie_consent#44] opened 2023-07-26 07:24 UTC
Hi there,

we did an update to mindshape_cookie_consent version 3.0.1 on Monday 24th.
Since then, we do get several entries in the log, here is the full log entry:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Mindshape\MindshapeCookieConsent\Service\CookieConsentService::__construct(): Argument #2 ($configurationRepository) must be of type Mindshape\MindshapeCookieConsent\Domain\Repository\ConfigurationRepository, Mindshape\MindshapeCookieConsent\Service\TemplateRenderingService given, called in /../typo3_src-11.5.29/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3249 | TypeError thrown in file /../typo3conf/ext/mindshape_cookie_consent/Classes/Service/CookieConsentService.php in line 96. Requested URL: xyz

We are using:
TYPO3 11.5.29
mindshape_cookie_consent 3.0.1
bootstrap_package: 13.0.2

Do you know how to fix this?

Thx in advance & best regards
Clea

**Comment by featdd** [comment] 2023-08-01 07:58
Hi @cbaumstark,

I wasn't really able to reproduce this, have you a valid configuration?

Greetings
Daniel

**Comment by cbaumstark** [comment] 2023-08-01 09:13
Hi @featdd,

I did not change the configuration for several months, so it has been the same before and after the update.
Is there anything else I could provide?

Thx & greetings,
Clea

**Comment by featdd** [comment] 2023-10-29 12:13
Hi @cbaumstark,

sorry for the late response, I'm still not able to reproduce this.
Could you have done anything else that influences the autoloading!?

Reading the error the autoloading tries to inject the TemplateRenderingService instead of the ConfigurationRepository, but the TemplateRenderingService is nowhere declared in the CookieConsentService...

I'll close this issue for now, but if you could provide more information or figure it out I will open it again.

Greetings
Daniel

**Closed by featdd** 2023-10-29 12:13 UTC

**Comment by cbaumstark** [comment] 2023-11-06 09:01
Hi @featdd,

the error has been provoked because the extension did not load the preview image due to privacy settings in the Vimeo videos. The Vimeo videos are only allowed to be embedded at specific domains. The extension has then not loaded the preview image and has thrown the error and did not show the whole Content Element any more.
Adapting ext_mindshape_cookie_consent\classes_viewhelpers\MediaConsentViewHelper.php has resolved the issue.

Greetings
Clea
