### ISSUE TITLE
Localisation not working

### ISSUE THREAD

**Issue by jonas-kuepper** [mindshape-GmbH/mindshape_cookie_consent#19] opened 2021-08-26 10:46 UTC
![Bildschirmfoto vom 2021-08-26 12-46-36](https://user-images.githubusercontent.com/89580323/130949731-5033679c-de1d-4f1e-80ea-20cb9f9450c8.png)
Line 54 in the methode findByUidIgnoreLanguage in the ConfigurationRepository prevents correct localisation in my project. All textlines that come from configuration (header, hint, buttons, show / hide details) are in the default language. Every other text is in the correct localised language. When I comment out this one line it works fine.
Does this line have a purpose I don't understand?

**Comment by featdd** [comment] 2021-09-15 12:13
Hi @jonas-kuepper,

where do you use the method, it isn't used by the extension in the frontend!?
The method is only used for the backend statistic module.

Greetings
Daniel

**Comment by 22markets** [comment] 2022-01-16 16:01
The Problem is in

mindshape_cookie_consent/Classes/Domain/Model/Configuration.php Line 340 in Version 2.1.1 in Versions below it might be another Line number. Search for getLanguageUid

public function getLanguageUid(): int

working with

public function getSysLanguageUid(): int.

@ Author
Please verify and fix

**Comment by featdd** [comment] 2022-01-22 14:19
Hi @22markets,

the method returns the translated records language uid, which in my testing, was correct so I can't really reproduce this issue.
I got an empty TYPO3 11.5.5 with german as default language and could create an english translation, the statistic module also counted properly for the english page only.

@jonas-kuepper does this issue still persist or was it caused by some other custom stuff?

I will close this issue as I'm unable to reproduce this for now, but please feel welcome to give me the steps necessary to reproduce this.

Greetings
Daniel

**Closed by featdd** 2022-01-22 14:19 UTC
