### ISSUE TITLE
TYPO3 Exception: syntax error, unexpected ')'

### ISSUE THREAD

**Issue by juergen1964** [mindshape-GmbH/mindshape_cookie_consent#42] opened 2023-07-09 15:38 UTC
Hi there,
after updating from version 2.2.5 to 3.0.1 i got this message in my backend log (protokoll):

`Core: Exception handler (CLI): Uncaught TYPO3 Exception: syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE) | ParseError thrown in file /mnt/......typo3conf/ext/mindshape_cookie_consent/Classes/Utility/SettingsUtility.php in line 42 `

TYPO3 Vers. 11.5.28
PHP: 8.1.19
Bootstrap Package: 13.0.2

I did not do any changes in my previous configuration (so far i know), so i wonder about that message. Got someone any idea what is wrong and how to fix it?

THX a lot and have a nice day

**Comment by featdd** [comment] 2023-07-09 19:43
Hi @juergen1964,

How and where did you get the exception, the path looks strange and it looks like it gets called over CLI!?

In the line is a catch block without variable name, this is legitimate to do since 8.0.
Are you sure you call the script or frontend with the right PHP version?

Greetings
Daniel

**Comment by juergen1964** [comment] 2023-07-09 20:59
Hi Daniel,
thx for your replay! No weekend? 

I agree it looks like it is coming from the CLI, thats what the message says. I only got one task running (sys_log task).

It looks like the message apeare every morning around the same time and pops up in the systeminfo tool on top of TYPO3 you know the red dot with the error messages. And there i got also the message of using php version 8.1.19 so i hope it is not ceating me.

Maybe i can roll back to the version 2.2.5 of the extension to see if the error disapear? What do You think? Or maybe others can report the same issue?

Have a nice monday! 
Jürgen

**Comment by featdd** [comment] 2023-07-10 14:35
Hi @juergen1964,

the error seems to be caused by the missing exception catch variable name, maybe you can hardcode a variable and see if the error persists. This would indicate that some older PHP version is calling your TYPO3 somehow.

Greetings
Daniel

**Comment by featdd** [comment] 2023-10-29 12:45
Hi @juergen1964,

as I'm unable to reproduce this myself I will close this issue for now.
If you have additional information and if theres a problem with the extension I will reopen this again.

Greetings
Daniel

**Closed by featdd** 2023-10-29 12:45 UTC
